### ISSUE TITLE
No Data Source selected , Please select a data source 

### ISSUE THREAD

**Issue by adeelmhr** [Kittyfisto/Tailviewer#122]
hello everyone, 
i am trying to connect OpenBCI to laptop in order to collect some data, but i am facing error "No Data Source selected , Please select a data source " and i am unable to select some source from LIVE (from Cyton

**Comment by Kittyfisto** [comment]
Hi, you have several options to open a log file:

1. Click Data Sources on the right (to open the side panel) and then click on the plus item:
![image](https://user-images.githubusercontent.com/11990827/31574766-71668f00-b0d6-11e7-8ba0-0ceda2f4a617.png)

2. Drag and drop a file from windows explorer over to tailviewer (this doesn't work immediately after installing because the installer starts Tailviewer with admin privileges, preventing drag'n drop, restarting tailviewer once fixes this issue).

**Comment by Kittyfisto** [comment]
@adeelmhr Still need help with this issue?
