### ISSUE TITLE
How to generate the Index.xml file to add the custom plugins 

### ISSUE THREAD

**Issue by abani1986** [Kittyfisto/Tailviewer#181]
### Current behaviour

For the existing plugins like "Tailviewer.Analysis.Count.0.7.tvp" it looks like it is a zip file which contains the dll and the index.xml file. When we create a new plugin I am not able to figure out how to generate the index.xml file. Without the index.xml file plugins are not loading.

### Expected behaviour

<Describe what you think should be happening>

### Steps to reproduce the problem

<Describe how to reproduce the problem, if possible>

**Comment by abani1986** [comment]
@Kittyfisto Could you please help me on this?

**Comment by Kittyfisto** [comment]
Sure thing, my documentation on how to create a plugin is still in a rough state and it seems I didn't even cover how to do this.

I assume you've already created a .NET Class Library in Visual Studio and referenced the latest Tailviewer.Api nuget package. Once this compiles, all you have to do is to add a custom build step which invokes an executable which is part of that nuget package like this:

1. Right click on your project in the Solution Explorer and Select Properties
2. Go to Build Events
3. Add the following into the Post-build event command line:

`archive pack <Assembly File Name>`, for example:

`
cd $(OutputDir)
archive pack Tailviewer.Analysis.QuickInfo.dll
`

In order for this to work, archive.exe should have been copied to the project's output directory which should automatically be the case (due to nuget referencing all assemblies in the nuget package).

Archiver will pack your assembly, all of its dependencies (and also automatically create and add that index.xml file) into a zip archive.

If you put that zip archive into the plugins folder (or have the post-build step do that automatically for you), then Tailviewer should recognize and load your plugin. However in order for this to work at this time, you have to download the latest Tailviewer version from my build server: https://ci.appveyor.com/project/Kittyfisto/sharptail

It won't work with the latest released Tailviewer version! I do plan on another release, but I don't have an ETA just yet.

Let me know if this helps.

**Comment by Kittyfisto** [comment]
I'm gonna assume that this has fixed the issue for you. If not, feel free to re-open and provide more details.
