### ISSUE TITLE
GUI - Colorize Titlebar 

### ISSUE THREAD

**Issue by Swiftpaws** [Kittyfisto/Tailviewer#202]
### Current behaviour

The titlebar is not colorized and thus does not adhere to focus gained / loss feedback.

### Expected behaviour

Please provide a way to colorize the titlebar (blue / grey) should work

**Comment by Kittyfisto** [comment]
Agreed, will be done with the next (0.9) update.

**Comment by Kittyfisto** [comment]
After taking a closer look at how other applications solve this, I've come up with the following design:

Focused:
![image](https://user-images.githubusercontent.com/11990827/61072354-63f75c00-a413-11e9-9622-f958b035cdfc.png)

Not focused:
![image](https://user-images.githubusercontent.com/11990827/61072365-68237980-a413-11e9-92f7-46b7517d10d2.png)

I've tried experimenting with different shades of blue but as it turns out I'm not much of a designer so I ended up with a gray color for the titlebar. You can check out the result for yourself by downloading the latest [CI build](https://ci.appveyor.com/project/Kittyfisto/sharptail/build/artifacts).

**Comment by Kittyfisto** [comment]
Fixed with [v0.9.0](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.9.0)
