### ISSUE TITLE
Merged data source: The origin of a log line should be apparent to the user

### ISSUE THREAD

**Issue by BenKenobi85** [Kittyfisto/Tailviewer#98]
When viewing a merged data source it sometimes is important to know which specific source file did contribute a specific line to the merged data source view. To accomplish this marking each line with a configurable background color depending on the originating source file would help. The same marker shall be visible in the file tree of the merge data source.

Example:

Merged data source view
-> Line 1: Source A : Color Yellow
-> Line 2: Source B : Color Blue
-> Line 3: Source A : Color Yellow

**Comment by Kittyfisto** [comment]
How would these colors work with the "Color by level" feature and the proposed "color by matching filter" feature? Is it enough, as the user, to select the coloring mode out of the three available? Or should multiple be visible at the same time?

**Comment by Kittyfisto** [comment]
@BenKenobi85 I've added an additional column next to the "line number" column which is only visible for merged data sources; the column displays the file name (up to 22 characters) of the original source of a line. You can check the current implementation in the [latest build](https://ci.appveyor.com/project/Kittyfisto/sharptail/build/artifacts) for yourself if you like.

Do you think that this is enough or should there be colors used in addition to that? If that's enough then I'll make this feature available in a release due to this week.

**Comment by BenKenobi85** [comment]
Having the extra column for filename is a good idea but does not help in case you have multiple logs merged each having the very same filename. Also the extra column tends to have much white-space so it's not very efficient with respect to effective usage of the available area for printing the log. In my opinion maximizing the usable space for log data is crucial.

I'd like to propose a different concept, see below:

![image](https://user-images.githubusercontent.com/26541111/31650687-d11e33c8-b318-11e7-81d5-22ccadd582e3.png)

The extra column just contains a small marker character referring to the originating data source, while data sources automatically are labeled with the marker character as well. Using a capital letter from A to Z - not sure if 26 labels are enough, could be extended to AA...ZZ - have a strong distinction to the line numbering. Not sure if additionally coloring each line according the linke data source helps or make the view more unsettled. In either case the coloring must consist of pastelish colors having a low saturation. I actually like the approach with black and grey font color, but how to proceed for more than 2 merged data sources?

**Comment by Kittyfisto** [comment]
@BenKenobi85 I agree on it wasting a lot of space. 

(Btw, those lines are gray because I've set the foreground color of DEBUG/TRACE messages to better separate them from INFO and other levels as I assume that debug is way less important - doesn't have anything to do with merging though)

I'm not ready to give up on this approach, but I also do like your solution. I'll implement yours in the next iteration and improve mine and introduce a toggle so you may choose which version to display (may I'll add another button to the already big list of buttons above, or you'll just have to click the column to toggle...).

My vision is to allow the user to chose (as others may value less space less important than the additional indirection of remembering [or constantly looking to the right] the letters) which version is used.

Also agree that using colors might be tricky, so I'll postpone it until we feel that the system in place is not sufficient for everyone anymore.

Do you have any suggestions as to what lettering scheme to use? I'll definitely start with having the first source be A, then B, etc... but I do wonder if having more persistent letters could be better to remember. Something along the lines of a particular file *always* gets A, regardless of order in the merged data source. This way you could simply memorize the link between A and the actual file instead of having to constantly look it up. What do you think?

**Comment by Kittyfisto** [comment]
Note to self: Do not forget to properly implement the limit of a maximum of 255 merged files.

**Comment by Kittyfisto** [comment]
First iteration has been finished and will appear in release 0.7.0

**Comment by Kittyfisto** [comment]
Released in 0.7.0
